### ISSUE TITLE
多个设备连接时查看DeviceInfo时多次弹出

### ISSUE THREAD

**Issue by lizhiwei92** [longforus/adb-idea#3]
1.多个设备连接时查看DeviceInfo时多次弹出，第一次使用时 很久才响应
版本v1.6.4，平台：windows

2.希望查看信息面板支持查找功能，毕竟一堆信息里面想找自己想要的关键字很费眼

**Comment by longforus** [comment]
好的 ，谢谢你的反馈，最近比较忙，有时间我会看一下

**Comment by longforus** [comment]
@lizhiwei92 v1.6.8已经修复
